cloud:
  # google_actions:
  #   filter:
  #     include_entities:
  #       - media_player.bathroom
  #       - media_player.living_room
  #   entity_config: !include_dir_merge_named ../assistants/google
  alexa:
    filter:
      include_entities:
        # Lights
        - light.balcony_group
        - light.bathroom_group
        - light.bedroom_group
        - light.bedroom_guests_group
        - light.corridor_group
        - light.entrance_group
        - light.kitchen_group
        - light.living_room_group
        - light.house_group
        - light.christmas_group
        # Switchs
        - switch.ventilation
        - switch.sonoff_100048cb54 #Bedroom closet
        - media_player.nvidia_shield
        # Inputs boolean
        - input_boolean.guest_mode
        # Plugs
        #- switch.circadian_lighting_circadian_lighting
        # Covers
    entity_config: !include_dir_merge_named ../assistants/alexa