life360:
  accounts:
    username: !secret integration_life360_username
    password: !secret integration_life360_password
  interval_seconds: 15
  members:
    include:
      - Laurent Bouriez
      - Giulia
      - Vincenzo
  max_update_wait:
    minutes: 30
  warning_threshold: 2
  error_threshold: 3
  circles:
    include: [Extended Family]