lovelace:
  mode: yaml
  resources:
    - url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
      type: js
    - url: /community_plugin/weather-card/weather-card.js
      type: module
    - url: /community_plugin/circle-sensor-card/circle-sensor-card.js
      type: module
    - url: /community_plugin/surveillance-card/surveillance-card.js
      type: module
    - url: /community_plugin/lovelace-layout-card/layout-card.js
      type: js
    - url: /community_plugin/lovelace-card-tools/card-tools.js
      type: js
    - url: /community_plugin/custom-header/custom-header.js
      type: module
    - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
      type: js
    - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /community_plugin/button-card/button-card.js
      type: module
    - url: /community_plugin/simple-thermostat/simple-thermostat.js
      type: module
    - url: /community_plugin/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
      type: js
    - url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
      type: module
    - url: /community_plugin/lovelace-toggle-lock-entity-row/toggle-lock-entity-row.js
      type: js
    - url: /community_plugin/lovelace-gui-sandbox/gui-sandbox.js
      type: module
    - url: /community_plugin/decluttering-card/decluttering-card.js
      type: module
    - url: /community_plugin/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /community_plugin/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js
      type: module
    - url: /community_plugin/banner-card/banner-card.js
      type: module
    - url: /community_plugin/lovelace-card-mod/card-mod.js
      type: module
    - url: /community_plugin/lovelace-swipe-navigation/swipe-navigation.js
      type: js
    - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
      type: module