# Depends of the History conponent - https://www.home-assistant.io/components/recorder/
recorder:
  purge_interval: 1
  purge_keep_days: 3
  db_url: mysql://hass:hass@core-mariadb/homeassistant?charset=utf8
  include:
    domains:
      - sensor
      - switch
      - media_player
  exclude:
    entities:
     - sensor.last_boot
     - sensor.date