path: areas.bedrooms.guests
title: Guest bedroom
icon: mdi:bed-queen
panel: false

badges:
  !include /config/config/lovelace/views/badges.yaml
  
cards:
  # Col 1
  - type: vertical-stack
    cards:
      # Lights
      - type: entities
        entity: light.bedroom_guests_group
        title: Lights
        entities: !include /config/config/lovelace/areas/bedrooms/guests/views/lights.yaml
      # Alarm house
      - !include /config/config/lovelace/areas/entrance/views/alarm_ring.yaml
  # Col 3
  - type: vertical-stack
    cards:
      # Sensors
      - type: entities
        title: 'Sensors'
        show_header_toggle: false
        entities:
          - sensor.group_temperature_guests_bedroom
          - type: divider
          - group.motion_guests_bedroom
      # Automations
      - type: custom:monster-card
        show_empty: false
        card:
          type: entities
          title: 'Automations'
          show_header_toggle: false
        filter:
          include:
            - entity_id: "automation.guests_*"
            - entity_id: "automation.corridor*"