type: custom:monster-card
show_empty: false
card:
  type: glance
  title: 'Water & smoke sensors'
  show_header_toggle: false
filter:
  include:
    - entity_id: "binary_sensor.water*"
    - entity_id: "binary_sensor.smoke*"