type: entities
title: 'Lights'
show_header_toggle: false
entities:
    - group.all_lights
    - light.balcony_group
    - light.bathroom_group
    - type: custom:fold-entity-row
      head: light.bedroom_group
      entity: light.bedroom_group
      entities: !include /config/config/lovelace/areas/bedrooms/main/views/lights.yaml
    - type: custom:fold-entity-row
      head: light.bedroom_guests_group
      entity: light.bedroom_guests_group
      entities: !include /config/config/lovelace/areas/bedrooms/guests/views/lights.yaml
    - light.corridor_group
    - type: custom:fold-entity-row
      head: light.entrance_group
      entity: light.entrance_group
      entities: !include /config/config/lovelace/areas/entrance/views/lights.yaml
    - type: custom:fold-entity-row
      head: light.kitchen_group
      entity: light.kitchen_group
      entities: !include /config/config/lovelace/areas/kitchen/views/lights.yaml
    - type: custom:fold-entity-row
      head: light.living_room_group
      entity: light.living_room_group
      entities: !include /config/config/lovelace/areas/living room/views/lights.yaml
    - type: divider
    - switch.circadian_lighting_circadian_lighting
    - switch.lights_ambiance_tv
    - type: custom:slider-entity-row
      entity: input_number.light_variable_brightness