type: custom:mini-media-player
artwork: cover
entity: media_player.living_room
hide:
  power: true
  icon: true
sonos:
  show_group_count: true
  entities:
    - entity_id: media_player.living_room
    - entity_id: media_player.bathroom