motions_sensor:
  name: Motion sensors
  icon: mdi:motion-sensor
  entities:
    - binary_sensor.bedroom_guests_sensor_motion
    - binary_sensor.entrance_sensor_motion
    - binary_sensor.bathroom_motion
    - binary_sensor.motion_foscam_c1
    - binary_sensor.motion_sensor_158d0002417b2e # Aqara Kitchen
    - binary_sensor.living_room # Ring Living room
    - binary_sensor.motion_detector_48836 # Ring Bedroom guests
    - binary_sensor.blink_entrance_motion_detected # Blink entrance
    - binary_sensor.blink_living_room_motion_detected # Blink living room
    - binary_sensor.blink_balcony_motion_detected # Blink balcony
    - binary_sensor.motion_sensor_158d0004140234 # Aqara Bedroom