alias: Bedroom guests - Alarm armed away
trigger:
  platform: state
  entity_id: alarm_control_panel.ring_alarm
  to: 'armed_away'
action:
  service: light.turn_off
  entity_id: light.bedroom_guests_group
