resources:
  !include /config/config/lovelace/ressources/ressources.yaml

custom_header:
  !include /config/config/lovelace/ressources/cch.yaml

decluttering_templates:
  !include_dir_named /config/config/lovelace/decluttering_templates

title: Casa nostra
background: var(--background-image)
views:
  !include_dir_list /config/config/lovelace/views