resources:
  !include /config/config/lovelace/ressources/ressources.yaml

cch:
  !include /config/config/lovelace/ressources/cch.yaml

decluttering_templates:
  !include_dir_named /config/config/lovelace/templates

title: Casa nostra
background: var(--background-image)
views:
  !include /config/config/lovelace/ressources/views.yaml