alias: Balcony - Lights auto off
initial_state: True
trigger:
  - platform: time
    at: '23:45:00'
condition:
  - condition: state
    entity_id: light.balcony_group
    state: 'on'
action:
  - service: light.turn_off
    entity_id: 'light.balcony_group'