type: custom:auto-entities
show_empty: false
card:
  type: glance
  title: 'Doors'
  show_header_toggle: false
filter:
  include:
    - entity_id: "group.door_*"
    - entity_id: "lock.*"
  exclude:
    - entity_id: group.door_all