type: custom:auto-entities
show_empty: false
card:
  type: glance
  title: 'Motion sensors'
  show_header_toggle: false
filter:
  include:
    - entity_id: "group.motion_*"
  exclude:
    - entity_id: group.motion_all
    - entity_id: group.motion_inside