camera_blink_trigger_camera:
  alias: Script - Blink take picture
  description: Take a picture of the moment on the camera to update the view in the blink app
  fields:
    name:
      description: 'Camera name'
      example: 'Entrance'
  sequence:
    - service: blink.trigger_camera
      data_template:
        name: "{{ name }}"
    - delay: 00:00:05
    - service: blink.blink_update
    - service: notify.laurent
      data_template:
        title: "Information"
        message: "|{{ name }}|"
        data:
          url: !secret integration_http_base_url
          priority: -1