lights_turn_off:
  alias: Script - Turn off lights
  description: Turn off lights with transition and ensure that it's off
  fields:
    entity_id:
      description: 'Entity id that has to be turned off'
      example: 'light.living_room'
  sequence:
    - service: 'light.turn_off'
      data_template:
        entity_id: "{{ entity_id }}"
        transition: 4
    - delay:
        seconds: 4
    - service: 'light.turn_off'
      data_template:
        entity_id: "{{ entity_id }}"