alias: Kitchen - Lights off
hide_entity: True
initial_state: True
trigger:
  - platform: state
    entity_id: group.motion_kitchen
    to: 'off'
    for:
      minutes: 2
  - platform: numeric_state
    entity_id: input_number.light_variable_brightness
    below: 1
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: 'light.kitchen_group'
      state: 'on'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
action:
  - service_template: 'light.turn_off'
    entity_id: 'light.kitchen_group'