alias: Kitchen - Remote long click
hide_entity: True
initial_state: True
trigger:
  platform: event
  event_type: xiaomi_aqara.click
  event_data:
    entity_id: binary_sensor.switch_158d00027b5181
    click_type: long_click_press
action:
  - event: event_toggle_ac