alias: Kitchen - Remote double click
initial_state: True
trigger:
  platform: event
  event_type: xiaomi_aqara.click
  event_data:
    entity_id: binary_sensor.switch_158d00027b5181
    click_type: double
action:
  - service: light.turn_off
    entity_id: 'light.kitchen_group'