alias: Kitchen - Remote single click
hide_entity: True
initial_state: True
trigger:
  platform: event
  event_type: xiaomi_aqara.click
  event_data:
    entity_id: binary_sensor.switch_158d00027b5181
    click_type: single
action:
  - service: light.turn_on
    entity_id: 'light.kitchen_group'
    data:
      brightness_pct: 100