# Exemple of nice confs:
# https://github.com/abeksis/My-HomeAssistant-Config/blob/41e51df1bb83b1024978c6ebb3a2df19e3ec1973/HomeAssistant_File/lovelace/cch/compact-custom-header.yaml
# https://github.com/Holewijn/Smarthome-Homeassistant-config/blob/master/lovelace/cch/compact-custom-header.yaml
main_config: true
background: 'rgba(0,0,0,0.3)'
menu: overflow
options: clock
voice: hide
hide_tabs: '11 to 100'
notifications: overflow
hide_config: true
hide_help: true
clock_format: '24'
clock_date: true
disable: false
swipe_skip: "3"
swipe: true
redirect: false
exceptions:
  - conditions:
      user_agent: Mobile
      media_query: "(max-width: 600px)"
      user: Laurent
    config:
      menu: hide
      options: hide
      default_tab: 'house.home'
  - conditions:
      user: Giulia, Vincenzo
    config:
      menu: hide
      options: hide
      kiosk_mode: true
      default_tab: 'house.home.light'
      hide_tabs: '1 to 100'