# Exemple of nice confs:
# https://github.com/abeksis/My-HomeAssistant-Config/blob/41e51df1bb83b1024978c6ebb3a2df19e3ec1973/HomeAssistant_File/lovelace/cch/compact-custom-header.yaml
# https://github.com/Holewijn/Smarthome-Homeassistant-config/blob/master/lovelace/cch/compact-custom-header.yaml
main_config: true
background: 'rgba(0,0,0,0.3)'
menu: overflow
options: clock
voice: hide
hide_tabs: 'house.cameras'
notifications: overflow
hide_config: true
hide_help: true
clock_format: '24'
clock_date: true
disable: false
exceptions:
  - conditions:
      user_agent: Mobile
      media_query: "(max-width: 600px)"
    config:
      menu: hide
      options: hide
      swipe: true
      swipe_skip: "3"
      swipe_animate: fade
      # kiosk_mode: true
