- !include /config/config/lovelace/house/main_view.yaml
- !include /config/config/lovelace/house/security.yaml
- !include /config/config/lovelace/house/admin.yaml
- title: '|'
- !include /config/config/lovelace/areas/living room/main_view.yaml
- !include /config/config/lovelace/areas/kitchen/main_view.yaml
- !include /config/config/lovelace/areas/entrance/main_view.yaml
- !include /config/config/lovelace/areas/bedrooms/main/main_view.yaml
- !include /config/config/lovelace/areas/bedrooms/guests/main_view.yaml
- !include /config/config/lovelace/areas/bathroom/main_view.yaml
- !include /config/config/lovelace/areas/balcony/main_view.yaml
- !include /config/config/lovelace/house/cameras.yaml
