path: admin
title: Administration
icon: mdi:home-assistant
background: radial-gradient(crimson, skyblue)
panel: true

cards:
  - type: vertical-stack
    cards:
      - type: custom:layout-card
        max_columns: 2
        layout: horizontal
        max_width: [50%, 50%]
        cards:
          # # Custom updated
          # - type: custom:tracker-card
          #   title: Card updates
          #   trackers:
          #     - sensor.custom_card_tracker
          #     - sensor.custom_component_tracker
          #     - sensor.custom_python_script_tracker
          - type: vertical-stack
            cards:
              # Battery almost done
              - type: custom:monster-card
                show_empty: false
                card:
                  type: glance
                  title: Low Battery Devices
                filter:
                  include:
                    - entity_id: "*battery_level*"
                      state: '< 25'
                    - attributes:
                        battery: '< 25'
                    - attributes:
                        battery_level: '< 25'
                  exclude:
                    - entity_id: lock.front_door
              # Things with issues
              - type: custom:monster-card
                show_empty: false
                card:
                  type: entities
                  title: Things that are broken
                  show_header_toggle: false
                filter:
                  include:
                    - state: "unknown"
                  exclude:
                    - entity_id: group.*
                    - entity_id: sensor.bedroom*
                    - entity_id: sensor.entrance
                    - entity_id: sensor.*bedrooms
                    - entity_id: sensor.kitchen_switch
              # Pi-hole
              - type: entities
                show_header_toggle: false
                title: Pi-hole
                entities:
                  - sensor.pi_hole_ads_blocked_today
                  - sensor.pi_hole_dns_queries_today
                  - sensor.pi_hole_dns_unique_clients
              # VM
              - type: entities
                show_header_toggle: false
                title: VM monitoring
                entities:
                  - sensor.last_boot
              - type: custom:layout-card
                max_columns: 2
                layout: horizontal
                max_width: [50%, 50%]
                cards:
                  - type: gauge
                    entity: sensor.processor_use
                    name: CPU
                    unit_of_measurement: '%'
                    min: 0
                    max: 100
                    severity:
                      yellow: 45
                      green: 10
                      red: 85
                  - type: gauge
                    entity: sensor.disk_use_percent
                    name: Disk
                    unit_of_measurement: '%'
                    min: 0
                    max: 100
                    severity:
                      yellow: 45
                      green: 90
                      red: 10
                  - type: gauge
                    entity: sensor.memory_free
                    name: Memory
                    unit_of_measurement: '%'
                    min: 0
                    max: 2000
                    severity:
                      yellow: 1200
                      green: 250
                      red: 1800
                  - type: gauge
                    entity: sensor.memory_use_percent
                    name: Memory
                    unit_of_measurement: '%'
                    min: 0
                    max: 100
                    severity:
                      yellow: 45
                      green: 90
                      red: 10
          # Syno
          - type: vertical-stack
            cards:
              - type: glance
                title: Syno monitoring
                entities:
                  #- sensor.average_disk_temp_volume_1
                  #- sensor.maximum_disk_temp_volume_1
                  #- sensor.disk_smart_status
                  - sensor.synology_dsm_status_volume_1
                  - sensor.synology_dsm_used_space_volume_1
                  - sensor.synology_dsm_network_up
              - type: custom:layout-card
                max_columns: 2
                layout: horizontal
                max_width: [50%, 50%]
                cards:
                  - type: entities
                    entities:
                      - type: weblink
                        name: Synology
                        url: !secret global_url_synology
                        icon: mdi:harddisk
                  - type: gauge
                    entity: sensor.synology_dsm_volume_used_volume_1
                    title: Disk
                    unit_of_measurement: '%'
                    min: 0
                    max: 100
                    severity:
                      yellow: 45
                      green: 10
                      red: 90
                  - type: gauge
                    entity: sensor.synology_dsm_cpu_load_total
                    title: CPU
                    unit_of_measurement: '%'
                    min: 0
                    max: 100
                    severity:
                      yellow: 45
                      green: 10
                      red: 90
                  - type: gauge
                    entity: sensor.synology_dsm_memory_usage_real
                    title: RAM
                    unit_of_measurement: '%'
                    min: 0
                    max: 100
                    severity:
                      yellow: 45
                      green: 10
                      red: 90
          # Automations
          - type: custom:monster-card
            show_empty: false
            card:
              type: entities
              title: 'Automations'
              show_header_toggle: false
            filter:
              include:
                - entity_id: "automation.*"
                