path: tv
title: TV
icon: mdi:television-classic
background: radial-gradient(crimson, skyblue)
panel: true

cards:
  - type: custom:layout-card
    max_columns: 3
    layout: horizontal
    max_width: [40%, 30%, 30%]
    cards:
      - type: map
        aspect_ratio: 16:9
        entities:
          - person.giulia
          - person.laurent
          - zone.home