alias: Alarm - Fix MQTT plugin
initial_state: True
trigger:
  - platform: state
    entity_id: alarm_control_panel.ring_alarm
  - platform: time_pattern
    minutes: '/30'
    seconds: 0
condition:
  condition: and
  conditions:
    - condition: template
      value_template: "{{ not is_state('alarm_control_panel.ring_alarm', 'disarmed') }}"
    - condition: template
      value_template: "{{ not is_state('alarm_control_panel.ring_alarm', 'armed_home') }}"
    - condition: template
      value_template: "{{ not is_state('alarm_control_panel.ring_alarm', 'armed_away') }}"
action:
  - service: hassio.addon_restart
    data:
      addon: 1c0fc3cd_ring_alarm
  - delay:
      minutes: 1
      seconds: 30