name: laurent_gmail
platform: smtp
sender: !secret integration_notify_laurent_gmail_sender
recipient:
  - !secret integration_notify_laurent_gmail_recipient
server: smtp.gmail.com
port: 587
username: !secret integration_notify_laurent_gmail_username
password: !secret integration_notify_laurent_gmail_password
timeout: 15
encryption: starttls
sender_name: Home Assistant