platform: template
lights:
  balcony:
    friendly_name: "Balcony"
    value_template: "{{ states('switch.tplink_b0_be_76_79_ea_25') }}"
    turn_on:
      service: switch.turn_on
      entity_id: switch.tplink_b0_be_76_79_ea_25
    turn_off:
      service: switch.turn_off
      entity_id: switch.tplink_b0_be_76_79_ea_25