platform: template
lights:
  kitchen_led:
    friendly_name: "Kitchen led"
    value_template: "{{ states('switch.kitchen_led') }}"
    turn_on:
      service: switch.turn_on
      entity_id: switch.kitchen_led
    turn_off:
      service: switch.turn_off
      entity_id: switch.kitchen_led