platform: template
lights:
  balcony:
    friendly_name: "Balcony"
    value_template: "{{ states('switch.tplink_hs200_balcony') }}"
    turn_on:
      service: switch.turn_on
      entity_id: switch.tplink_hs200_balcony
    turn_off:
      service: switch.turn_off
      entity_id: switch.tplink_hs200_balcony