alias: Living room - A/C on for bedroom
hide_entity: True
initial_state: True
trigger:
  - platform: numeric_state
    entity_id: sensor.group_temperature_bedroom
    above: 25.5
condition:
  condition: and
  conditions:
    # Bedroom temperature
    - condition: numeric_state
      entity_id: sensor.group_temperature_bedroom
      above: 25.5
    # Weather outside
    - condition: template
      value_template: "{{ state_attr('weather.dark_sky', 'temperature') | float > 25 }}"
    - condition: state
      entity_id: climate.living_room
      state: 'off'
action:
  - service: climate.turn_on
    entity_id: climate.living_room
  - service: script.notify
    data:
      notify_id: laurent
      priority: 0
      title: "A/C"
      message: "The A/C has been turned on"