alias: Living room - Lights christmas on
hide_entity: True
initial_state: True
trigger:
  platform: state
  entity_id: alarm_control_panel.ring_alarm
  to: 'disarmed'
action:
  - service: light.turn_on
    data:
      entity_id: light.christmas