alias: Living room - Lights christmas on
hide_entity: True
initial_state: True
trigger:
  - platform: time
    at: '18:30:00'
action:
  - service: light.turn_on
    data:
      entity_id: light.christmas