alias: Living room - Remote hue
hide_entity: True
initial_state: True
trigger:
  - platform: state
    entity_id: sensor.living_room
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: 'sensor.living_room'
      state: '4_click_up'
    - condition: state
      entity_id: 'sensor.living_room'
      state: '4_click'
    - condition: state
      entity_id: 'sensor.living_room'
      state: '1_click_up'
    - condition: state
      entity_id: 'sensor.living_room'
      state: '1_click'
    - condition: state
      entity_id: 'sensor.living_room'
      state: '1_hold_up'
    - condition: state
      entity_id: 'sensor.living_room'
      state: '1_hold'
action:
  - service_template: >
      {% if (is_state("sensor.living_room", "4_click_up")) or (is_state("sensor.living_room", "4_click")) %}
        light.turn_off
      {% elif (is_state("sensor.living_room", "1_hold_up")) or (is_state("sensor.living_room", "1_hold")) %}
        light.turn_off
      {% elif (is_state("sensor.living_room", "1_click_up")) or (is_state("sensor.living_room", "1_click")) %}
        light.turn_on
      {% endif %}
    entity_id: light.table_spots