alias: Living room - Ambiance TV off
trigger:
  # - platform: state
  #   entity_id: switch.harmony_tv
  #   from: 'on'
  #   to: 'off'
  - platform: state
    entity_id: media_player.living_room_v
    to: 'off'
action:
  service: light.turn_off
  entity_id: light.living_room_group