alias: Living room - Ambiance TV on
trigger:
  # - platform: state
  #   entity_id: switch.harmony_tv
  #   from: 'off'
  #   to: 'on'
  - platform: state
    entity_id: media_player.living_room_v
    from: 'off'
    to: 'standby'
  - platform: state
    entity_id: media_player.living_room_v
    from: 'off'
    to: 'playing'
condition:
  - condition: state
    entity_id: 'switch.lights_ambiance_tv'
    state: 'off'
action:
  service: switch.turn_on
  entity_id: switch.lights_ambiance_tv