alias: Living room - Ambiance TV on
trigger:
  - platform: state
    entity_id: media_player.living_room_v
    from: 'off'
condition:
  - condition: state
    entity_id: 'switch.lights_ambiance_tv'
    state: 'off'
action:
  - service: light.turn_off
    entity_id: light.living_room_group
  - service: switch.turn_on
    entity_id: switch.lights_ambiance_tv