alias: Living room - Ambiance TV off
trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    to: 'off'
action:
  - service: light.turn_off
    entity_id: light.living_room_group
  - condition: time
    after: '22:00:00'
  - service: 'script.lights_turn_on_with_delay'
    data:
      entity_id: 'light.corridor_group'
      delay_minutes: 3
      brightness_pct: 10