alias: Living room - Ambiance TV playing
trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    to: 'paused'
  - platform: state
    entity_id: media_player.living_room_tv
    to: 'standby'
action:
  - service: script.light_turn_on_if_necessary
    data:
      entity_id: 'light.living_room_spots'
      brightness_pct: 20
  - service: light.turn_off
    entity_id: light.kitchen_group