alias: Living room - Ambiance TV playing
trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    from: 'off'
    to: 'paused'
  - platform: state
    entity_id: media_player.living_room_tv
    from: 'off'
    to: 'standby'
action:
  - service: light.turn_on
    entity_id: light.living_room_group
    data:
      brightness_pct: 20
  - service: light.turn_off
    entity_id: light.kitchen_group