alias: Living room - Ambiance TV off
trigger:
  - platform: state
    entity_id: media_player.living_room_v
    to: 'off'
action:
  - service: light.turn_off
    entity_id: light.living_room_group
  - condition: time
    after: '22:00:00'
  - service: light.turn_on
    data:
      entity_id: light.corridor_group
      brightness_pct: 10
  - delay:
      minutes: 3
  - service: light.turn_off
    entity_id: light.corridor_group