alias: Living room - Ambiance TV off
trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    from: 'playing'
    to: 'off'
    for:
      seconds: 30
  - platform: state
    entity_id: media_player.living_room_tv
    from: 'standby'
    to: 'off'
    for:
      seconds: 30
condition:
  - condition: time
    after: '18:30:00'
    before: '07:00:00'
action:
  - service: light.turn_off
    entity_id: light.living_room_group
  - condition: time
    after: '22:00:00'
  - service: script.turn_off
    data:
      entity_id: script.light_turn_on_then_off
  - service: 'script.light_turn_on_then_off'
    data:
      entity_id: 'light.living_room_group'
      delay_minutes: 3
      brightness_pct: 2