alias: Living room - Ambiance TV on
trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    to: 'playing'
action:
  - service: switch.turn_on
    entity_id: switch.lights_ambiance_tv