alias: Living room - Ambiance TV on
trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    to: 'playing'
action:
  - service: scene.turn_on
    entity_id: scene.living_room_ambiance_tv