alias: Living room - Ambiance TV playing
trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    from: 'off'
    to: 'playing'
  - platform: state
    entity_id: media_player.living_room_tv
    from: 'standby'
    to: 'playing'
  - platform: state
    entity_id: media_player.living_room_tv
    from: 'paused'
    to: 'playing'
condition:
  - condition: time
    after: '19:00:00'
action:
  - service: scene.turn_on
    entity_id: scene.living_room_ambiance_tv