alias: Living room - Vacuum start when away
trigger:
  - platform: state
    entity_id: alarm_control_panel.ring_alarm
    to: 'armed_away'
  - platform: time
    at: '16:00:00'
condition:
  # condition: state
  # entity_id: vacuum.living_room
  # state: 'docked'
  # for:
  #   hours: 4 # With 8 it was not working
  - condition: template
    value_template: "{{ (is_state('vacuum.living_room', 'docked')) and (((as_timestamp(now()) - as_timestamp(states.vacuum.living_room.attributes.clean_stop))) > 28800) }}"
action:
  - service: vacuum.start
    entity_id: vacuum.living_room
  - service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.living_room
      fan_speed: 'Max'
