alias: Living room - Vava reboot
trigger:
  - platform: time
    at: '04:00:00'
action:
  - service: switch.turn_off
    entity_id: switch.vava_base
  - delay:
      minutes: 1
  - service: switch.turn_on
    entity_id: switch.vava_base