alias: Entities - Fix ring addon
initial_state: True
trigger:
  - platform: homeassistant
    event: start
action:
  # - service: switch.turn_on
  #   entity_id: switch.alarm_toggle_away
  - service: automation.turn_off
    entity_id: automation.alarm_check_alarm
  - delay:
      minutes: 1
  - service: hassio.addon_restart
    data:
      addon: 1c0fc3cd_ring_alarm
  - delay:
      seconds: 25
  - service: automation.turn_on
    entity_id: automation.alarm_check_alarm
