alias: Entities - Refresh IOT link
hide_entity: True
initial_state: True
trigger:
  - platform: homeassistant
    event: start
action:
  - delay:
      minutes: 1
  - service: mqtt.publish
    data:
      topic: iotlink/workgroup/nuc/refresh