alias: System - Home Assistant startup automations delayed
initial_state: True
trigger:
  - platform: homeassistant
    event: start
action:
  # Automations
  - service: automation.turn_off
    entity_id:
      - automation.alarm_fix_mqtt_plugin_and_notify
  - delay:
      minutes: 2
  - service: automation.turn_on
    entity_id:
      - automation.alarm_fix_mqtt_plugin_and_notify