alias: System - Home Assistant startup notification
hide_entity: True
initial_state: True
trigger:
  - platform: homeassistant
    event: start
action:
  - service: notify.laurent
    data_template:
      title: "Information"
      message: Home Assistant has just been started
      data:
        priority: -1
        url: !secret integration_http_base_url
        timestamp: true
        expire: 3600
        retry: 30