alias: System - Home Assistant startup fix tracker state
hide_entity: True
initial_state: True
trigger:
  - platform: homeassistant
    event: start
action:
  - delay:
      seconds: 45
  - event: event_fix_tracker