alias: System - Reboot if connection is down
hide_entity: true
initial_state: true
trigger:
  - platform: state
    entity_id: binary_sensor.lan
    to: 'off'
    for:
      minutes: 3
  - platform: state
    entity_id: binary_sensor.wan
    to: 'off'
    for:
      minutes: 3
action:
  - service: persistent_notification.create
    data:
      title: Home Assistant was down!
      message: 'Home Assistant disconneted from router - rebooting hassio...'
      notification_id: hassio_upgrade
  - service: script.notify
    data:
      notify_id: everyone
      priority: 2
      title: "Alert"
      message: 'Home Assistant disconneted from router - rebooting hassio...'
  - service: hassio.host_reboot




  