alias: Alarm - Notify Alarm Triggered
hide_entity: True
initial_state: True
trigger:
  - platform: state
    entity_id: alarm_control_panel.ring_alarm
    to: 'triggered'
action:
  - service: notify.everyone
    data:
      title: "Alert"
      data:
        url: !secret integration_http_base_url
        priority: 2
        timestamp: true
        expire: 3600
        retry: 30
      message: "The alarm has been triggered, immediately check the house !"