alias: Alarm - Toggle Alarm
hide_entity: True
initial_state: True
trigger:
  - platform: event
    event_type: event_toggle_alarm
action:
  - service_template: >
      {%- if is_state('alarm_control_panel.ring_alarm', 'disarmed') -%}
        alarm_control_panel.alarm_arm_home
      {%- else -%}
        alarm_control_panel.alarm_disarm
      {%- endif -%}
    entity_id: alarm_control_panel.ring_alarm