alias: Alarm - Check alarm
hide_entity: True
initial_state: True
trigger:
  - platform: state
    entity_id: group.all_family
    from: 'home'
    to: 'not_home'
    for:
      minutes: 5
  - platform: time_pattern
    hours: '/1'
    minutes: 0
    seconds: 0
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: 'alarm_control_panel.ring_alarm'
      state: 'disarmed'
    - condition: state
      entity_id: 'group.all_family'
      state: 'not_home'
action:
  - service: notify.everyone
    data:
      title: "Alert"
      data:
        url: !secret integration_http_base_url
        priority: 1
        timestamp: true
        expire: 3600
        retry: 30
      message: 'The alarm is not on... Is it normal ?'