alias: Camera - Update blink picture
hide_entity: True
initial_state: True
trigger:
  - platform: time_pattern
    hours: '/1'
    minutes: 0
    seconds: 0
  - platform: event
    event_type: event_camera_blink_trigger_picture
action:
  - service: script.turn_on
    entity_id: script.blink_trigger_camera