alias: Entrance - Lock front door
hide_entity: True
initial_state: True
trigger:
  - platform: event
    event_type: event_lock_front_door
  - platform: state
    entity_id: group.door_entrance
    from: 'on'
    to: 'off'
# condition:  
#   - condition: template
#     value_template: '{{ not is_state("lock.front_door", "loked") }}'
action:
  - service: lock.lock
    entity_id: lock.front_door