alias: Entrance - Ventilation
initial_state: True
trigger:
  - platform: state
    entity_id: group.motion_inside
    to: 'on'
  - platform: time
    at: '11:00:00'
condition:
  condition: and
  conditions:
    - condition: time
      after: '06:30:00'
      before: '21:00:00'
action:
  - service: switch.turn_on
    entity_id: switch.ventilation