platform: template
switches:
  alarm_toggle_blink:
    friendly_name: 'Blink armed'
    icon_template: mdi:alarm-light
    value_template: "{{ is_state('alarm_control_panel.blink_home', 'armed_away') }}"
    turn_on:
      - service: alarm_control_panel.alarm_arm_away
        entity_id: alarm_control_panel.blink_home
    turn_off:
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.blink_home