platform: circadian_lighting
name: Circadian lighting
lights_brightness:
  # Bedroom
  - light.bedroom_group
  # Living room
  - light.living_room_group
  # Kitchen
  - light.kitchen_group
  # Entrance
  - light.entrance_group
  # Bathroom
  - light.bathrrom_group
lights_rgb:
  # Bedroom
  - light.bedroom_2
  - light.bedroom_1
  - light.bedroom_led
  # Living room
  - light.living_color
  - light.tv_led_1
  - light.tv_led_2
  # Kitchen
  - light.kitchen_led_strip
lights_ct:
  # Bedroom guests
  - light.berdoom_guests_1
  - light.bedroom_guests_2
  # Kitchen
  - light.bake_left
  - light.bake_right
  # Corridor
  - light.corridor_bedrooms