platform: template
switches:
  heat_bedroom:
    friendly_name: 'Heat Bedroom'
    icon_template: mdi:thermometer
    value_template: "{{ is_state('input_boolean.heat_bedroom', 'on') }}"
    turn_on:
      - service: input_boolean.turn_on
        entity_id: input_boolean.heat_bedroom
      - service: ifttt.trigger
        data_template:
          event: casa_temperature_set_bedroom
          value1: "{{ state_attr('climate.bedroom_heat', 'temperature')}}"
    turn_off:
      - service: input_boolean.turn_off
        entity_id: input_boolean.heat_bedroom
      - service: ifttt.trigger
        data_template:
          event: casa_temperature_set_bedroom
          value1: 5
  heat_living_room:
    friendly_name: 'Heat Living room'
    icon_template: mdi:thermometer
    #value_template: "{{ (states.climate.living_room.attributes.temperature) | float > (states.sensor.temperature_158d000245a7d5.state) | float }}"
    value_template: "{{ is_state('input_boolean.heat_living_room', 'on') }}"
    turn_on:
      - service: input_boolean.turn_on
        entity_id: input_boolean.heat_living_room
      - service: ifttt.trigger
        data_template:
          event: casa_temperature_set_living_room
          value1: "{{ state_attr('climate.living_room_heat', 'temperature')}}"
    turn_off:
      - service: input_boolean.turn_off
        entity_id: input_boolean.heat_living_room
      - service: ifttt.trigger
        data_template:
          event: casa_temperature_set_living_room
          value1: 5