platform: template
switches:
  heat_bedroom:
    friendly_name: 'Heat Bedroom'
    icon_template: mdi:thermometer
    value_template: "{{ is_state('input_boolean.heat_bedroom', 'on') }}"
    turn_on:
      - service: input_boolean.turn_on
        entity_id: input_boolean.heat_bedroom
      - service: ifttt.trigger
        data_template:
          event: casa_temperature_set_bedroom
          value1: "{{ state_attr('climate.bedroom_heat', 'temperature')}}"
    turn_off:
      - service: input_boolean.turn_off
        entity_id: input_boolean.heat_bedroom
      - service: ifttt.trigger
        data_template:
          event: casa_temperature_set_bedroom
          value1: 5