alias: Living room - Magic cube disabled
hide_entity: True
initial_state: True
trigger:
  - platform: event
    event_type: app_daemon_magic_cube
    event_data:
      entity_id: magic_cube
      action_type: shake_air
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.cube_mode
      option: 'Disable'