alias: Living room - Magic cube fall sonos pause
hide_entity: True
initial_state: True
trigger:
  - platform: event
    event_type: app_daemon_magic_cube
    event_data:
      entity_id: magic_cube
      action_type: tap_twice
condition:
  - condition: state
    entity_id: input_select.cube_mode
    state: 'Sonos'
  - condition: state
    entity_id: 'media_player.living_room'
    state: 'playing'
action:
  - service: media_player.media_pause
    data:
      entity_id: media_player.living_room