alias: Living room - Magic cube rotate brightness
hide_entity: True
initial_state: True
trigger:
  - platform: event
    event_type: app_daemon_magic_cube
    event_data:
      entity_id: magic_cube
      action_type: rotate
condition:
  - condition: state
    entity_id: input_select.cube_mode
    state: 'Light'
action:
  - service: light.turn_on
    data_template:
      entity_id: light.living_room_group
      brightness: >
        {%if trigger.event.data.action_value | float > 0 %}
          {% set bri = state_attr('light.living_room_group', 'brightness') | int %}
          {{ [bri+15, 249] | min }}
        {% else %}
          {% set bri = state_attr('light.living_room_group', 'brightness') | int %}
          {{ [bri-15, 0] | max }}
        {% endif %}