alias: Kitchen - Magic cube double tap light
initial_state: True
trigger:
  - platform: event
    event_type: app_daemon_magic_cube
    event_data:
      entity_id: magic_cube
      action_type: tap_twice
condition:
  - condition: state
    entity_id: input_select.cube_mode
    state: 'Disable'
action:
  - service_template: >
      {%- if is_state('light.kitchen_group', 'off') -%}
        light.turn_on
      {%- else -%}
        light.turn_off
      {%- endif -%}
    entity_id: light.kitchen_group