alias: Living room - Magic cube move next source
hide_entity: True
initial_state: True
trigger:
  - platform: event
    event_type: app_daemon_magic_cube
    event_data:
      entity_id: magic_cube
      action_type: move
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_select.cube_mode
      state: 'Sonos'
    - condition: state
      entity_id: 'media_player.living_room'
      state: 'playing'
    - condition: template
      value_template: '{{ states.media_player.living_room.attributes.source != "TV" }}'
action:
  - service: media_player.media_next_track
    data:
      entity_id: media_player.living_room