alias: House - Magic cube enable light
hide_entity: True
initial_state: True
trigger:
  - platform: event
    event_type: app_daemon_magic_cube
    event_data:
      entity_id: magic_cube
      action_type: flip180
condition:
  - condition: state
    entity_id: input_select.cube_mode
    state: 'Sonos' 
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.cube_mode
      option: 'Light'