path: areas.bathroom
title: Bathroom
icon: mdi:shower
panel: true

cards:
  - type: vertical-stack
    cards:
      - type: custom:layout-card
        max_columns: 2
        layout: horizontal
        max_width: [50%, 50%]
        cards:
          # Col 1
          - type: vertical-stack
            cards:
              # Lights
              - type: entities
                entity: light.bathroom_group
                title: Lights
                entities: !include /config/config/lovelace/areas/bathroom/views/lights.yaml
              # Switches
              - type: entities
                title: 'Actions'
                show_header_toggle: false
                entities:
                  - !include /config/config/lovelace/areas/bathroom/views/media_player_sonos.yaml
                  # - !include /config/config/lovelace/areas/bathroom/views/media_player_alexa.yaml
          # Col 3
          - type: vertical-stack
            cards:
              # Sensors
              - type: entities
                title: 'Sensors'
                show_header_toggle: false
                entities:
                  - sensor.group_temperature_bathroom
                  - type: divider
                  - group.motion_bathroom
              # Automations
              - type: custom:monster-card
                show_empty: false
                card:
                  type: entities
                  title: 'Automations'
                  show_header_toggle: false
                filter:
                  include:
                    - entity_id: "automation.bathroom_*"