# No more than 6 for the mobile view to be good
- type: state-label
  entity: sun.sun
  name: Go home
  tap_action:
    action: navigate
    navigation_path: 'house.home.light'
  double_tap_action:
    action: more-info
- type: entity-filter
  entities:
    - entity: group.door_all
      name: 'Doors'
  state_filter:
    - "on"
- type: entity-filter
  entities:
    - entity: group.motion_all
      name: 'Motions'
  state_filter:
    - "on"
- entity: sensor.group_temperature_all
  name: 'Temperature'
# Alarms
- entity: alarm_control_panel.ring_alarm
- entity: alarm_control_panel.alexa_guard_851bb
  name: 'Guard'
- entity: alarm_control_panel.blink_home