type: custom:auto-entities
show_empty: false
card:
  type: entities
  title: Things that are broken
  show_header_toggle: false
filter:
  include:
    - state: "unknown"
  exclude:
    - entity_id: group.*
    - entity_id: sensor.*edroom*
    - entity_id: sensor.entrance
    - entity_id: sensor.kitchen_switch
    - entity_id: sensor.*_dot_*
    - entity_id: sensor.bouriez_s_sonos_one_*
    - entity_id: sensor.*_next*