type: custom:vertical-stack-in-card
title: Coronavirus
cards:
- type: custom:mini-graph-card
  color_thresholds:
  - color: '#e74c3c'
    value: 50000
  - color: '#ffff00'
    value: 25000
  - color: '#1db954'
    value: 0
  entities:
    - entity: sensor.italy_confirmed
      index: 0
    - entity: sensor.italy_deaths
      index: 0
    - entity: sensor.italy_current
      index: 0
  font_size: 65
  height: 46
  hours_to_show: 168
  line_width: 2
  name: Italy
  points_per_hour: 1
  show:
    extrema: true
    icon: false
- type: custom:mini-graph-card
  color_thresholds:
  - color: '#e74c3c'
    value: 2000
  - color: '#ffff00'
    value: 1000
  - color: '#1db954'
    value: 0
  entities:
    - entity: sensor.canada_confirmed
      index: 0
    - entity: sensor.canada_deaths
      index: 0
    - entity: sensor.canada_current
      index: 0
  font_size: 65
  height: 46
  hours_to_show: 168
  line_width: 2
  name: Canada
  points_per_hour: 1
  show:
    extrema: true
    icon: false
- type: custom:mini-graph-card
  color_thresholds:
  - color: '#e74c3c'
    value: 15000
  - color: '#ffff00'
    value: 7500
  - color: '#1db954'
    value: 0
  entities:
    - entity: sensor.france_coronavirus_confirmed
      index: 0
    - entity: sensor.france_coronavirus_deaths
      index: 0
    - entity: sensor.france_coronavirus_current
      index: 0
  font_size: 65
  height: 46
  hours_to_show: 168
  line_width: 2
  name: France
  points_per_hour: 1
  show:
    extrema: true
    icon: false
- type: custom:mini-graph-card
  color_thresholds:
  - color: '#e74c3c'
    value: 300000
  - color: '#ffff00'
    value: 150000
  - color: '#1db954'
    value: 0
  entities:
    - entity: sensor.worldwide_confirmed
      index: 0
    - entity: sensor.worldwide_deaths
      index: 0
    - entity: sensor.worldwide_current
      index: 0
  font_size: 65
  height: 46
  hours_to_show: 168
  line_width: 2
  name: Worldwide
  points_per_hour: 1
  show:
    extrema: true
    icon: false