type: custom:xiaomi-vacuum-card
entity: vacuum.living_room
image: /local/img/vacuum.png
name: Xiaomi Vacuum
buttons: true
labels:
  status: Etat
  battery: Batterie
  mode: Puissance
  main_brush: Brosse Principale
  side_brush: Brosse Latérale
  filter: Filtre
  sensor: Capteurs