path: house.admin
title: Administration
icon: mdi:home-assistant
panel: false

badges:
  !include ../views/divers_badges.yaml

popup_cards: []

cards:
  # Col 1
  - type: vertical-stack
    cards:
      # Battery almost done
      - !include ../includes/low_battery_devices.yaml
      # Things with issues
      - !include ../includes/broken_entities.yaml
      - !include ../includes/bottom-card.yaml
      # Pi-hole
      - !include ../views/admin_monitoring_pi_hole.yaml
      # VM
      - !include ../views/admin_monitoring_vm.yaml
      - !include ../includes/bottom-card.yaml
  # Col 3
  - type: vertical-stack
    cards:
      # Synology
      - !include ../views/admin_monitoring_synology.yaml
      # Automations
      - type: custom:auto-entities
        show_empty: false
        card:
          type: entities
          title: 'Automations'
          show_header_toggle: false
        filter:
          include:
            - entity_id: "automation.system*"
            - entity_id: "automation.entities*"
      - !include ../includes/bottom-card.yaml