path: areas.bedrooms.guests
title: Guest bedroom
icon: mdi:bed-queen
panel: false

badges:
  !include ../includes/_badges.yaml

popup_cards: []

cards:
  # Col 1
  - type: vertical-stack
    cards:
      - !include ../includes/footer_card.yaml
      # Lights
      - type: entities
        entity: light.bedroom_guests_group
        title: Lights
        entities: !include ../includes/entities/lights_guests-bedroom.yaml
      # Alarm house
      - !include ../includes/areas/entrance/alarm_ring.yaml
      - !include ../includes/bottom-card.yaml
  # Col 2
  - type: vertical-stack
    cards:
      # Sensors
      - type: entities
        title: 'Sensors'
        show_header_toggle: false
        entities:
          - sensor.group_temperature_guests_bedroom
          - type: divider
          - group.motion_guests_bedroom
      # Automations
      - type: custom:auto-entities
        show_empty: false
        card:
          type: entities
          title: 'Automations'
          show_header_toggle: false
        filter:
          include:
            - entity_id: "automation.guests_*"
            - entity_id: "automation.corridor*"
      - !include ../includes/bottom-card.yaml