path: temp.coronavirus
title: Coronavirus map
icon: mdi:biohazard
panel: true

cards:
  - type: iframe
    url: >-
      https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6
    aspect_ratio: 100%