type: custom:monster-card
show_empty: false
card:
  type: glance
  title: Low Battery Devices
filter:
  include:
    - entity_id: "*battery_level*"
      state: '< 25'
    - attributes:
        battery: '< 25'
    - attributes:
        battery_level: '< 25'
  exclude:
    - entity_id: lock.front_door