# https://community.home-assistant.io/t/lovelace-badge-notification-banner/62074
type: picture-elements    
image: /local/img/banner.png
elements:
  - type: state-badge
    entity: sensor.time
    style:
      top: 50%
      left: 5%
  - type: state-badge
    entity: alarm_control_panel.ring_alarm
    style:
      top: 50%
      left: 15%
  - type: state-badge
    entity: binary_sensor.balcony
    style:
      top: 50%
      left: 25%