type: conditional
conditions:
  - entity: group.all_family
    state: 'not_home'
card:
  type: custom:auto-entities
  show_empty: false
  card:
    title: You forgot to turn off
    type: entities
  filter:
    include:
      - entity_id: switch.*led
        state: 'on'
      - entity_id: light.*
        state: 'on'
      - entity_id: media_player.*
        state: 'on'
    exclude:
      - entity_id: "light.extended_*"
      - entity_id: "light.gateway_*"