type: custom:monster-card
show_empty: false     
card:
  title: You forgot to turn off
  type: entities
filter:
  include:
    - entity_id: switch.*led
      state: 'on'
    - entity_id: light.*
      state: 'on'
    - entity_id: media_player.*
      state: 'on'
  exclude:
    - entity_id: "light.extended_*"
    - entity_id: "light.gateway_*"
when:
  entity: group.all_family
  state: 'not_home'