type: vertical-stack
cards:
- type: picture-glance
  entities:
    - entity: person.laurent
    - entity: person.giulia
    - entity: person.vincenzo
  image: /local/img/tracker_at_home.jpg
  title: "Family"
  state_image:
    "not_home": /local/img/tracker_away.jpg
    "home": /local/img/tracker_at_home.jpg
  entity: group.all_family