path: house.admin
title: Administration
icon: mdi:home-assistant
panel: true

cards:
  - type: vertical-stack
    cards:
      - type: custom:layout-card
        max_columns: 2
        layout: horizontal
        max_width: [50%, 50%]
        cards:
          # Col 1
          - type: vertical-stack
            cards:
              # Battery almost done
              - !include /config/config/lovelace/house/views/admin_battery_dead.yaml
              # Things with issues
              - !include /config/config/lovelace/house/views/admin_entities_broken.yaml
              # Pi-hole
              - !include /config/config/lovelace/house/views/monitoring_pi_hole.yaml
              # VM
              - !include /config/config/lovelace/house/views/monitoring_vm.yaml
          # Col 3
          - type: vertical-stack
            cards:
              # Synology
              - !include /config/config/lovelace/house/views/monitoring_synology.yaml 
              # Automations
              - type: custom:monster-card
                show_empty: false
                card:
                  type: entities
                  title: 'Automations'
                  show_header_toggle: false
                filter:
                  include:
                    - entity_id: "automation.system*"
                    - entity_id: "automation.entities*"