path: house.security
title: Security
icon: mdi:shield
panel: false

badges:
  !include /config/config/lovelace/views/badges.yaml

cards:
  # Col 1
  - type: vertical-stack
    cards:
      - !include /config/config/lovelace/areas/entrance/views/alarm_ring.yaml
      - type: glance
        entities: !include /config/config/lovelace/house/views/group_all.yaml
      # Camera
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            name: Cameras
            tap_action:
              action: navigate
              navigation_path: /lovelace/house.cameras
      - type: horizontal-stack
        cards:
          - !include /config/config/lovelace/areas/living room/views/camera_blink.yaml
          - !include /config/config/lovelace/areas/living room/views/camera_foscam.yaml
      - type: horizontal-stack
        cards:
          - !include /config/config/lovelace/areas/entrance/views/camera_blink.yaml
          - !include /config/config/lovelace/areas/balcony/views/camera_blink.yaml
      - !include /config/config/lovelace/house/views/group_all_door.yaml
  # Col 2
  - type: vertical-stack
    cards:
      # Tracker
      - !include /config/config/lovelace/house/views/tracker_all.yaml
      - !include /config/config/lovelace/house/views/group_all_motion.yaml
      - !include /config/config/lovelace/house/views/group_all_temperature.yaml
  # Col 3
  - type: vertical-stack
    cards:
      - !include /config/config/lovelace/house/views/group_all_water_smoke.yaml
      # Automations
      - type: custom:monster-card
        show_empty: false
        card:
          type: entities
          title: 'Automations'
          show_header_toggle: false
        filter:
          include:
            - entity_id: "automation.alarm*"
            - entity_id: "automation.camera*"
            - entity_id: "automation.security*"
            - entity_id: "automation.person*"