alias: Entities - Fix tracker state
hide_entity: True
initial_state: True
trigger:
  - platform: event
    event_type: event_fix_tracker
  - platform: template
    value_template: "{% if is_state('group.all_family', 'unknown') %}true{% endif %}"
condition:
  condition: and
  conditions:
    - condition: template
      value_template: "{% if not is_state('device_tracker.life360_laurent_bouriez', 'home') %}true{% endif %}"
    - condition: template
      value_template: "{% if not is_state('device_tracker.life360_giulia', 'home') %}true{% endif %}"
action:
  - service: python_script.set_state
    data_template:
      entity_id: group.all_family
      state: 'not_home'
