alias: House - Absent from home
hide_entity: True
initial_state: True
trigger:
  - platform: time_pattern
    minutes: '/30'
    seconds: 0
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: 'group.all_family'
      state: 'not_home'
    - condition: or
      conditions:
        - condition: state
          entity_id: 'group.all_lights'
          state: 'on'
        # The group state on media_player doesn't work...
        - condition: state
          entity_id: 'media_player.bathroom'
          state: 'playing'
        - condition: state
          entity_id: 'media_player.living_room'
          state: 'playing'
        - condition: state
          entity_id: 'switch.harmony_tv'
          state: 'on'
action:
  - service: notify.everyone
    data_template:
      title: "Alert"
      data:
        url: !secret integration_http_base_url
        priority: -1
      message: >
        {% set light_on = states | selectattr('entity_id', 'in', state_attr('group.all_lights','entity_id')) | selectattr('state','eq','on') | map(attribute='name') | join(', ') %}
        {% set speaker_on = states | selectattr('entity_id', 'in', state_attr('group.sonos','entity_id')) | selectattr('state','eq','playing') | map(attribute='name') | join(', ') %}
        {% set tv_on = states | selectattr('entity_id', 'in', 'switch.harmony_tv') | selectattr('state','eq','on') | map(attribute='name') | join(', ') %}
        Some
        {% if lights != '' %}
        lights ({{ light_on }}),
        {% endif %}
        {% if speaker_on != '' %}
        speakers ({{ speaker_on }}),
        {% endif %}
        {% if is_state('switch.harmony_tv', 'on') %}
        tv ({{ tv_on }})
        {% endif %}
        were left on. I turned them off for you !
  - service: switch.turn_off
    entity_id: switch.harmony_tv
  - service: media_player.media_stop
    entity_id: group.sonos
  # To not conflict with Presence simulator or Alexa guard
  - condition: time
    before: '19:30:00'
  - service: light.turn_off
    entity_id: group.all_lights
  
  
  