alias: Security - Door left open
hide_entity: True
initial_state: True
trigger:
  - platform: state
    entity_id: group.all_family
    from: 'home'
    to: 'not_home'
condition:
  - condition: state
    entity_id: 'group.doors'
    state: 'on'
action:
  - service: notify.everyone
    data_template:
      title: "Alert"
      data:
        url: !secret integration_http_base_url
        priority: 2
        timestamp: true
        expire: 3600
        retry: 30
      message: >
        {% set unlocked = states | selectattr('entity_id', 'in', state_attr('group.doors','entity_id')) | selectattr('state','eq','on') | map(attribute='name') | join(', ') %}
        You forgot to close ({{ unlocked }}) !