platform: template
sensors:
  group_temperature_bathroom:
    friendly_name: "Bathroom"
    unit_of_measurement: '°C'
    icon_template: mdi:oil-temperature
    value_template: >-
      {{ ((states('sensor.bathroom_temperature_deconz')|float + states('sensor.shower_temperature_deconz')|float) / 2) | round(2) }}