platform: template
sensors:
  group_temperature_all:
    friendly_name: "All temperatures"
    unit_of_measurement: '°C'
    icon_template: mdi:oil-temperature
    value_template: >-
      {{ ((states('sensor.group_temperature_living_room')|float + states('sensor.group_temperature_bedroom')|float + states('sensor.group_temperature_guests_bedroom')|float + states('sensor.group_temperature_bathroom')|float + states('sensor.group_temperature_entrance')|float) / 5) | round(2) }}
