platform: template
sensors:
  group_temperature_bathroom:
    friendly_name: "Bathroom"
    unit_of_measurement: '°C'
    icon_template: mdi:oil-temperature
    value_template: >-
      {{ ((states('sensor.entrance_sensor_2_temperature')|float) / 1) | round(2) }}
