platform: template
sensors:
  group_temperature_entrance:
    friendly_name: "Entrance"
    unit_of_measurement: '°C'
    icon_template: mdi:oil-temperature
    value_template: >-
      {{ ((states('sensor.entrance_sensor_temperature')|float + states('sensor.blink_entrance_temperature')|float) / 2) | round(2) }}
