platform: template
sensors:
  group_temperature_bedroom:
    friendly_name: "Bedroom"
    unit_of_measurement: '°C'
    icon_template: mdi:oil-temperature
    value_template: >-
      {{ ((states('sensor.temperature_158d0002461865')|float) / 1) | round(2) }}
