default:
  - content: content

card:
  type: markdown
  style: |
    ha-card {
      box-shadow: none;
      height: 33px;
      background: none;
      padding: 0px 10px;
      color: var(--header-color);
    }
  content: '[[content]]'