alias: Bathroom - Lights off
hide_entity: True
initial_state: True
trigger:
  - platform: state
    entity_id: group.motion_bathroom
    to: 'off'
    for:
      minutes: 2
condition:
  - condition: state
    entity_id: 'light.bathroom_group'
    state: 'on'
action:
  - service_template: 'light.turn_off'
    entity_id: 'light.bathroom_group'