alias: Bathroom - Lights on
hide_entity: True
initial_state: True
trigger:
  - platform: state
    entity_id: group.motion_bathroom
    to: 'on'
  - platform: state
    entity_id: input_number.light_variable_brightness
condition:
  condition: and
  conditions:
    - condition: numeric_state
      entity_id: input_number.light_variable_brightness
      above: 0
    - condition: template
      value_template: "{{ not is_state('alarm_control_panel.ring_alarm', 'armed_away') }}"
    - condition: or
      conditions:
        - condition: template
          value_template: "{{ (trigger.entity_id == 'group.motion_bathroom') and is_state('light.bathroom_group', 'off') }}"
        - condition: template
          value_template: "{{ (trigger.entity_id == 'input_number.light_variable_brightness') and is_state('light.bathroom_group', 'on') }}"
action:
  # # Issue on bathroom not turning on the light
  - service: 'light.turn_on'
    entity_id: 'light.bathroom_group'
    data_template:
      brightness_pct: '{{ states("input_number.light_variable_brightness") | int }}'
  - condition: state
    entity_id: 'light.bathroom_group'
    state: 'off'
  - service: 'light.turn_on'
    entity_id: 'light.bathroom_group'
    data_template:
      brightness_pct: '{{ (states("input_number.light_variable_brightness") | int) + 10 }}'