alias: Bathroom - Lights off fix issue
hide_entity: True
initial_state: True
trigger:
  - platform: state
    entity_id: light.bathroom_group
    to: 'on'
condition:
  - condition: state
    entity_id: group.motion_bathroom
    state: 'off'
    for:
      seconds: 30
  - condition: time
    before: '06:45:00'
action:
  - service_template: 'light.turn_off'
    entity_id: 'light.bathroom_group'
  - service: script.notify
    data:
      notify_id: laurent
      priority: 0
      title: "Fix light bathroom"
      persistent_notification: True
      persistent_notification_id: light_bathroom_fix
      message: I turned off the light because it was on and shouldnt have...