alias: Security - Motion detected
hide_entity: True
initial_state: True
trigger:
  - platform: state
    entity_id: group.motion_all
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: 'group.all_family'
      state: 'not_home'
    - condition: template
      value_template: '{{ not is_state("vacuum.living_room", "cleaning") }}'
action:
  - event: event_camera_blink_trigger_picture
  - service: script.notify
    data:
      notify_id: everyone
      priority: 1
      title: "Alert"
      message: >
        {% set motion = states | selectattr('entity_id', 'in', state_attr('group.motion_all','entity_id')) | selectattr('state','eq','on') | map(attribute='name') | join(', ') %}
        Motion detected in: {{ motion }}