alias: Security - Door left open
hide_entity: True
initial_state: True
trigger:
  - platform: state
    entity_id: group.all_family
    from: 'home'
    to: 'not_home'
condition:
  - condition: state
    entity_id: 'group.door_all'
    state: 'on'
action:
  - service: script.notify
    data:
      notify_id: everyone
      priority: 2
      title: "Alert"
      message: >
        {% set unlocked = states | selectattr('entity_id', 'in', state_attr('group.door_all','entity_id')) | selectattr('state','eq','on') | map(attribute='name') | join(', ') %}
        You forgot to close ({{ unlocked }}) !