alias: System - HACS update alert
hide_entity: True
initial_state: True
trigger:
  - platform: numeric_state
    entity_id: sensor.hacs
    above: 0
  - platform: homeassistant
    event: start
condition:
  - condition: numeric_state
    entity_id: 'sensor.hacs'
    above: 0
action:
  - service: persistent_notification.create
    data_template:
      title: HACS update available
      message: >-
        There is a new update available in HACS
      notification_id: hacs_upgrade
