alias: Information - Coronavirus
initial_state: True
trigger:
  - platform: time
    at: '09:00:00'
  - platform: time
    at: '12:00:00'
  - platform: time
    at: '17:00:00'
action:
  - service: script.notify
    data:
      notify_id: everyone
      priority: 0
      title: "Coronavirus update"
      message: |
        --- Worldwide ---
        Total: {{ states('sensor.worldwide_confirmed') }} | Deaths: {{ states('sensor.worldwide_deaths') }} | Current: {{ states('sensor.worldwide_current') }}
        --- Italy ---
        Total: {{ states('sensor.italy_confirmed') }} | Deaths: {{ states('sensor.italy_deaths') }} | Current: {{ states('sensor.italy_current') }}
        --- Canada ---
        Total: {{ states('sensor.canada_confirmed') }} | Deaths: {{ states('sensor.canada_deaths') }} | Current: {{ states('sensor.canada_current') }}
        --- France ---
        Total: {{ states('sensor.france_coronavirus_confirmed') }} | Deaths: {{ states('sensor.france_coronavirus_deaths') }} | Current: {{ states('sensor.france_coronavirus_current') }}
