alias: System - Hass update alert
hide_entity: True
initial_state: True
trigger:
  - platform: state
    entity_id: sensor.version_available
  - platform: homeassistant
    event: start
condition:
  - condition: template
    value_template: >-
      {{
        states('sensor.version_available')
        !=
        states('sensor.version_current')
      }}
action:
  - service: script.notify
    data:
      notify_id: laurent
      priority: 0
      title: "New Home Assistant Release"
      message: >-
        There is a Home Assistant upgrade for Hass.io pending!
        Version {{ states('sensor.version_available') }} just got released!
  - service: persistent_notification.create
    data_template:
      title: Upgrade time!
      message: >-
        There is a Home Assistant upgrade for Hass.io pending!
        Version {{ states('sensor.version_available') }} just got released!
      notification_id: hassio_upgrade
