bathroom:
  sensor:
    - group.motion_bathroom
  entity:
    - light.bathroom_group
  sensor_type: duration
  delay: 240
  service_data:
    brightness_pct: 100
  start_time: '07:00:00'
  end_time: '23:45:00'
  night_mode:
    delay: 240
    service_data:
      brightness_pct: 50
    start_time: '22:00:00'
    end_time: '23:45:00'