kitchen:
  sensor:
    - group.motion_kitchen
  entity:
    - light.kitchen_group
  sensor_type: duration
  delay: 120
  service_data:
    brightness_pct: 100 # input_number.light_variable_brightness soom I hope...
  start_time: '09:00:00'
  end_time: '23:45:00'
  overrides:
    - input_boolean.guest_mode
  night_mode:
    delay: 60
    service_data:
      brightness_pct: 30
    start_time: '22:00:00'
    end_time: '23:45:00'