alias: Entities - Battery checker
hide_entity: True
initial_state: True
trigger:
  - platform: time_pattern
    hours: '/6'
    minutes: 0
    seconds: 0
condition:
  - condition: template
    value_template: >
        {{ selectattr('attributes.battery_level','<', (states.input_number.battery_alert_threshold.state | round(0)) ) | list | length >= 1 }}
  #- condition: template
  #  value_template: '{% for entity_id in states.group.battery_levels.attributes.entity_id if ((states(entity_id) | int)) < (states.input_number.battery_alert_threshold.state | round(0)) %} {%- if loop.first -%} {{ true }} {%- endif -%} {% endfor %}'
action:
  - service: notify.laurent
    data_template:
      title: "Alert"
      data:
        url: !secret integration_http_base_url
        priority: 0
      message: >
          {%- set low_batteries = states | selectattr('attributes.battery_level', 'defined') | selectattr('attributes.battery_level','<', (states.input_number.battery_alert_threshold.state | round(0)) ) | map(attribute='name') | list | join(', ') -%}
          Low batteries detected in somes devices ({{ low_batteries }})