alias: Bedroom - Alarm armed away
trigger:
  - platform: state
    entity_id: alarm_control_panel.ring_alarm
    to: 'armed_away'
condition:
  - condition: time
    before: '17:00:00'
action:
  - service: cover.open_cover
    data:
      entity_id: cover.bedroom_1