alias: Bedroom - Reboot Soma connect
trigger:
  - platform: time
    at: '15:00:00'
action:
  - service: switch.turn_off
    data:
      entity_id: switch.sonoff_100086f608
  - delay:
      seconds: 8
  - service: switch.turn_on
    data:
      entity_id: switch.sonoff_100086f608