alias: Bedroom - Lights off
initial_state: True
trigger:
  - platform: state
    entity_id: 'group.motion_bedroom'
    to: 'off'
    for:
      minutes: 5
condition:
  - condition: state
    entity_id: 'light.bedroom_group'
    state: 'on'
action:
  - service: 'light.turn_off'
    data:
      entity_id: 'light.bedroom_group'