alias: Bedroom - Lights on
hide_entity: True
initial_state: True
trigger:
  - platform: state
    entity_id: 'binary_sensor.motion_sensor_158d0004140234'
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: time
      after: '08:30:00'
      before: '23:30:00'
    - condition: state
      entity_id: 'light.bedroom_group'
      state: 'off'
action:
  - service: 'light.turn_on'
    entity_id: 'light.bedroom_group'
    data_template:
      brightness_pct: >
        {% if now().hour >= 22 %}25{% else %}100{% endif%}