alias: Bedroom - Lights off
hide_entity: True
initial_state: True
trigger:
  - platform: state
    entity_id: 'group.motion_bedroom'
    to: 'off'
    for:
      minutes: 5
  - platform: numeric_state
    entity_id: input_number.light_variable_brightness
    below: 1
condition:
  - condition: state
    entity_id: 'light.bedroom_group'
    state: 'on'
action:
  - service: 'script.lights_turn_off'
    data:
      entity_id: 'light.bedroom_group'