alias: Bedroom - Lights off
hide_entity: True
initial_state: True
trigger:
  - platform: state
    entity_id: 'binary_sensor.motion_sensor_158d0004140234'
    to: 'off'
    for:
      minutes: 5
condition:
  - condition: state
    entity_id: 'light.bedroom_group'
    state: 'on'
action:
  - service: 'script.lights_turn_off'
    data:
      entity_id: 'light.bedroom_group'