alias: Bedroom - Remote laurent long click
initial_state: True
trigger:
  platform: event
  event_type: xiaomi_aqara.click
  event_data:
    entity_id: binary_sensor.switch_158d000253d163
    click_type: long_click_press
action:
  - service: switch.toggle # Toggle ac during summer
    entity_id: switch.alarm_toggle_home