alias: Bedroom - Remote laurent
hide_entity: True
initial_state: True
trigger:
  - platform: state
    entity_id: sensor.bedroom_bed
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: 'sensor.bedroom_bed'
      state: '4_click_up'
    - condition: state
      entity_id: 'sensor.bedroom_bed'
      state: '4_click'
action:
  - service_template: >
      {% if is_state("sensor.bedroom_bed", "4_click_up") %}
        light.turn_off
      {% elif is_state("sensor.bedroom_bed", "4_click") %}
        light.turn_off
      {% endif %}
    entity_id: light.kitchen_led