alias: Bedroom - Remote laurent long click
hide_entity: True
initial_state: True
trigger:
  platform: event
  event_type: xiaomi_aqara.click
  event_data:
    entity_id: binary_sensor.switch_158d000253d163
    click_type: long_click_press
action:
  - event: event_toggle_alarm # Toggle ac during summer