name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome. Thanks for your first issue, I will look into it very soon.'
        pr-message: 'Welcome. Thanks for your first contribution to my repo.'
